# Generated by Django 6.0.5 on 2026-05-19 21:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Nom d'une icône ou classe CSS", max_length=50)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=150, verbose_name="Nom de l'entreprise/marque")),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name="SIRET/SIREN ou N° d'enregistrement")),
                ('is_verified', models.BooleanField(default=False, verbose_name='Profil vérifié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='profiles.category', verbose_name="Secteur d'activité")),
            ],
            options={
                'verbose_name': 'Profil Entreprise',
                'verbose_name_plural': 'Profils Entreprise',
            },
        ),
        migrations.CreateModel(
            name='InfluencerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tarif de base estimé')),
                ('instagram_username', models.CharField(blank=True, max_length=100)),
                ('tiktok_username', models.CharField(blank=True, max_length=100)),
                ('youtube_channel', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False, verbose_name='Profil vérifié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='influencers', to='profiles.category', verbose_name='Niches / Domaines')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Influenceur',
                'verbose_name_plural': 'Profils Influenceur',
            },
        ),
        migrations.CreateModel(
            name='InfluencerMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('other', 'Autre')], max_length=20)),
                ('followers_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'abonnés")),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name="Taux d'engagement (%)")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='profiles.influencerprofile')),
            ],
            options={
                'verbose_name': 'Métrique Influenceur',
                'verbose_name_plural': 'Métriques Influenceur',
                'unique_together': {('profile', 'platform')},
            },
        ),
    ]
