# Generated by Django 6.0.5 on 2026-05-22 19:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_category_icon_remove_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='influencermetric',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='influencermetric',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='base_rate',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='instagram_username',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='tiktok_username',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='youtube_channel',
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='influencers', to='profiles.category', verbose_name='Niches / Domaines'),
        ),
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('twitter', 'Twitter / X'), ('facebook', 'Facebook'), ('snapchat', 'Snapchat'), ('linkedin', 'LinkedIn'), ('other', 'Autre')], max_length=20, verbose_name='Plateforme')),
                ('profile_url', models.URLField(verbose_name='Lien du profil')),
                ('followers', models.PositiveIntegerField(default=0, verbose_name="Nombre d'abonnés")),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='profiles.influencerprofile')),
            ],
            options={
                'verbose_name': 'Plateforme sociale',
                'verbose_name_plural': 'Plateformes sociales',
                'ordering': ['platform'],
                'unique_together': {('profile', 'platform')},
            },
        ),
        migrations.DeleteModel(
            name='BusinessProfile',
        ),
        migrations.DeleteModel(
            name='InfluencerMetric',
        ),
    ]
