# Generated by Django 6.0.5 on 2026-05-22 20:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_influencermetric_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255, verbose_name="Nom de l'entreprise / de la marque")),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name="Secteur d'activité")),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('description', models.TextField(blank=True, verbose_name="Description de l'entreprise")),
                ('is_verified', models.BooleanField(default=False, verbose_name='Entreprise vérifiée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Entreprise',
                'verbose_name_plural': 'Profils Entreprise',
            },
        ),
    ]
