# Generated by Django 6.0.5 on 2026-06-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_target_categories'),
        ('categories', '0001_initial'),
        ('profiles', '0004_businessprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='influencers', to='categories.category', verbose_name='Niches / Domaines'),
        ),
    ]
