# Generated by Django 6.0.5 on 2026-06-11 15:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_delete_category_alter_influencerprofile_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='account_type',
            field=models.CharField(choices=[('individual', 'Particulier / Artiste'), ('organization', 'Organisation / Entreprise')], default='individual', max_length=20, verbose_name='Type de compte'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='niu',
            field=models.CharField(blank=True, help_text='Optionnel. Le NIU renforce la crédibilité du dossier.', max_length=50, null=True, verbose_name="NIU (Numéro d'Identifiant Unique)"),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='verification_note',
            field=models.TextField(blank=True, help_text='Visible par le partenaire. Expliquer le motif de rejet ou les corrections à apporter.', verbose_name="Note de l'administrateur"),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='verification_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='verification_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='verification_status',
            field=models.CharField(choices=[('none', 'Non soumis'), ('pending', 'En attente de révision'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='none', max_length=20, verbose_name='Statut de vérification'),
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_name', models.CharField(help_text='Ex : CNI, Récépissé, RCCM, Passeport, Attestation fiscale…', max_length=150, verbose_name='Nom du document')),
                ('file', models.FileField(help_text='PDF, JPG ou PNG. Max 5 Mo.', upload_to='verification_documents/%Y/%m/', verbose_name='Fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='profiles.businessprofile')),
            ],
            options={
                'verbose_name': 'Document de vérification',
                'verbose_name_plural': 'Documents de vérification',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
