# Generated by Django 6.0.5 on 2026-06-22 11:58

import config.utils.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_businessprofile_account_type_businessprofile_niu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdocument',
            name='file',
            field=models.FileField(help_text='PDF, JPG ou PNG. Max 5 Mo.', upload_to='verification_documents/%Y/%m/', validators=[config.utils.file_validators.validate_document_extension], verbose_name='Fichier'),
        ),
    ]
