# Generated by Django 6.0.5 on 2026-06-05 17:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0003_remove_campaign_max_influencers_and_more'),
        ('profiles', '0005_delete_category_alter_influencerprofile_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover_message', models.TextField(help_text="L'influenceur présente sa motivation, son audience, et explique pourquoi il est le bon profil pour cette campagne.", verbose_name='Message de candidature')),
                ('proposed_rate', models.DecimalField(blank=True, decimal_places=2, help_text="Optionnel. Si l'influenceur souhaite proposer un tarif différent du budget indiqué dans la campagne.", max_digits=10, null=True, verbose_name='Tarif proposé (€)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('withdrawn', "Retirée par l'influenceur"), ('in_progress', 'En cours'), ('completed', 'Terminée')], default='pending', max_length=20, verbose_name='Statut')),
                ('enterprise_note', models.TextField(blank=True, help_text="Visible par l'influenceur. Motif de refus ou message d'accompagnement.", verbose_name="Note de l'entreprise")),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de candidature')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de révision')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de complétion')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='campaigns.campaign', verbose_name='Campagne')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='profiles.influencerprofile', verbose_name='Influenceur')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-applied_at'],
                'unique_together': {('campaign', 'influencer')},
            },
        ),
    ]
