# Generated by Django 6.0.5 on 2026-06-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='completed_at',
        ),
        migrations.AddField(
            model_name='application',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='Set automatically when the enterprise accepts the application.', null=True, verbose_name="Date d'acceptation"),
        ),
        migrations.AlterField(
            model_name='application',
            name='proposed_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Optionnel. Si l'influenceur souhaite proposer un tarif différent du budget indiqué dans la campagne.", max_digits=10, null=True, verbose_name='Tarif proposé (FCFA)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Set on any final decision: accepted, rejected, or withdrawn.', null=True, verbose_name='Date de révision'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('withdrawn', "Retirée par l'influenceur")], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
