# Generated by Django 6.0.5 on 2026-06-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0002_remove_application_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='origin',
            field=models.CharField(choices=[('influencer', "Candidature de l'influenceur"), ('partner', 'Invitation du partenaire')], default='influencer', max_length=20, verbose_name='Origine'),
        ),
    ]
