# Generated by Django 6.0.5 on 2026-06-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('business', 'Entreprise'), ('influencer', 'Influenceur'), ('administrator', 'Administrateur')], max_length=20, null=True),
        ),
    ]
