# Generated by Django 6.0.5 on 2026-05-27 08:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0004_businessprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la campagne')),
                ('description', models.TextField(verbose_name='Description globale')),
                ('deliverables_brief', models.TextField(help_text='Ex : 1 Reel Instagram, 2 Stories, 1 vidéo YouTube…', verbose_name='Brief et livrables attendus')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Budget global (€)')),
                ('deadline', models.DateField(verbose_name='Date limite de candidature')),
                ('max_influencers', models.PositiveIntegerField(default=1, help_text='Combien de créateurs recherchez-vous pour cette campagne ?', verbose_name="Nombre max d'influenceurs")),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('open', 'Ouverte'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='profiles.businessprofile', verbose_name='Entreprise')),
                ('target_categories', models.ManyToManyField(blank=True, help_text="Niches d'influenceurs recherchés pour cette campagne.", related_name='campaigns', to='profiles.category', verbose_name='Catégories ciblées')),
            ],
            options={
                'verbose_name': 'Campagne',
                'verbose_name_plural': 'Campagnes',
                'ordering': ['-created_at'],
            },
        ),
    ]
