# Generated by Django 6.0.5 on 2026-06-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='target_categories',
            field=models.ManyToManyField(blank=True, help_text="Niches d'influenceurs recherchés pour cette campagne.", related_name='campaigns', to='categories.category', verbose_name='Catégories ciblées'),
        ),
    ]
