# Generated by Django 6.0.5 on 2026-06-05 10:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_target_categories'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='max_influencers',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='target_categories',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('open', 'Ouverte'), ('paused', 'En pause'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='CampaignCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_categories', to='campaigns.campaign')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_categories', to='categories.category')),
            ],
            options={
                'verbose_name': 'Catégorie de campagne',
                'verbose_name_plural': 'Catégories de campagne',
                'unique_together': {('campaign', 'category')},
            },
        ),
    ]
