# Generated by Django 6.0.5 on 2026-06-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_remove_campaign_max_influencers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='duration',
            field=models.CharField(blank=True, help_text='Ex: 2 semaines, 1 mois, etc.', max_length=100, null=True, verbose_name='Durée'),
        ),
    ]
